"""generate_docs.py — Auto-generate CLI reference and plugin inventory for MkDocs.

Usage:
    python scripts/generate_docs.py

Outputs:
    docs/cli_generated.md    — Full CLI reference from Typer help output
    docs/plugins_inventory.md — Discovered plugins listed by entry point group

Run this before `mkdocs build` to keep the docs in sync with the codebase.
To integrate with CI:
    python scripts/generate_docs.py && mkdocs build
"""
from __future__ import annotations

import importlib.metadata
import subprocess
import sys
from pathlib import Path

DOCS_DIR = Path(__file__).parent.parent / "docs"
REPO_ROOT = Path(__file__).parent.parent


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _run_cli(*args: str) -> str:
    """Run a ubunye CLI command and return stdout."""
    result = subprocess.run(
        [sys.executable, "-m", "ubunye.cli.main", *args],
        capture_output=True,
        text=True,
        cwd=str(REPO_ROOT),
    )
    return result.stdout.strip()


def _get_entry_points(group: str) -> dict[str, str]:
    """Return {name: module:class} for an entry point group."""
    eps = importlib.metadata.entry_points(group=group)
    return {ep.name: ep.value for ep in eps}


# ---------------------------------------------------------------------------
# CLI reference generator
# ---------------------------------------------------------------------------

_TOP_LEVEL_COMMANDS = [
    ("init",     ["init", "--help"]),
    ("validate", ["validate", "--help"]),
    ("plan",     ["plan", "--help"]),
    ("run",      ["run", "--help"]),
    ("plugins",  ["plugins", "--help"]),
    ("config",   ["config", "--help"]),
    ("version",  ["version", "--help"]),
]

_SUB_COMMAND_GROUPS = {
    "lineage": ["show", "list", "compare", "search", "trace"],
    "models":  ["list", "info", "promote", "demote", "rollback", "archive", "compare"],
}


def generate_cli_reference() -> str:
    lines = [
        "# CLI Reference (auto-generated)",
        "",
        "!!! note",
        '    This page is generated by `scripts/generate_docs.py`.',
        "    Run `python scripts/generate_docs.py` to refresh.",
        "",
        "---",
        "",
    ]

    # Top-level help
    lines += [
        "## `ubunye --help`",
        "",
        "```",
        _run_cli("--help"),
        "```",
        "",
        "---",
        "",
    ]

    # Per top-level command
    for cmd_name, args in _TOP_LEVEL_COMMANDS:
        output = _run_cli(*args)
        lines += [
            f"## `ubunye {cmd_name}`",
            "",
            "```",
            output,
            "```",
            "",
            "---",
            "",
        ]

    # Sub-command groups
    for group, sub_commands in _SUB_COMMAND_GROUPS.items():
        group_help = _run_cli(group, "--help")
        lines += [
            f"## `ubunye {group}`",
            "",
            "```",
            group_help,
            "```",
            "",
        ]
        for sub in sub_commands:
            sub_help = _run_cli(group, sub, "--help")
            lines += [
                f"### `ubunye {group} {sub}`",
                "",
                "```",
                sub_help,
                "```",
                "",
            ]
        lines += ["---", ""]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Plugin inventory generator
# ---------------------------------------------------------------------------

_PLUGIN_GROUPS = {
    "ubunye.readers":    "Readers",
    "ubunye.writers":    "Writers",
    "ubunye.transforms": "Transforms",
    "ubunye.monitors":   "Monitors",
}


def generate_plugin_inventory() -> str:
    lines = [
        "# Plugin Inventory (auto-generated)",
        "",
        "!!! note",
        '    This page is generated by `scripts/generate_docs.py`.',
        "    Run `python scripts/generate_docs.py` to refresh.",
        "",
        "---",
        "",
    ]

    for group, title in _PLUGIN_GROUPS.items():
        eps = _get_entry_points(group)
        lines += [f"## {title}", ""]
        if not eps:
            lines += ["_No plugins discovered._", ""]
            continue
        lines += ["| Name | Implementation |", "|---|---|"]
        for name, value in sorted(eps.items()):
            lines.append(f"| `{name}` | `{value}` |")
        lines += [""]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    print("Generating CLI reference...")
    cli_ref = generate_cli_reference()
    out_cli = DOCS_DIR / "cli_generated.md"
    out_cli.write_text(cli_ref, encoding="utf-8")
    print(f"  Written: {out_cli}")

    print("Generating plugin inventory...")
    plugin_inv = generate_plugin_inventory()
    out_plugins = DOCS_DIR / "plugins_inventory.md"
    out_plugins.write_text(plugin_inv, encoding="utf-8")
    print(f"  Written: {out_plugins}")

    print("Done. Run `mkdocs build` or `mkdocs serve` to preview.")


if __name__ == "__main__":
    main()
